# Generated by Django 4.1.1 on 2022-10-02 13:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAvailableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=10, verbose_name='Id del conductor')),
                ('schedule', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('delivery_latitude', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Latitud de entrega')),
                ('delivery_longitude', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Longitud de entrega')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_latitude', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Latitud de recogida')),
                ('pickup_longitude', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Longitud de recogida')),
                ('driver_available', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.driveravailablemodel', verbose_name='order_driver_available')),
            ],
        ),
        migrations.AddConstraint(
            model_name='driveravailablemodel',
            constraint=models.UniqueConstraint(fields=('driver', 'schedule'), name='driver_shedule'),
        ),
    ]
