# Generated by Django 4.1.1 on 2022-10-02 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveravailablemodel',
            name='delivery_latitude',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Latitud de entrega'),
        ),
        migrations.AlterField(
            model_name='driveravailablemodel',
            name='delivery_longitude',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Longitud de entrega'),
        ),
        migrations.AlterField(
            model_name='driveravailablemodel',
            name='schedule',
            field=models.DateTimeField(db_index=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='pickup_latitude',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Latitud de recogida'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='pickup_longitude',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Longitud de recogida'),
        ),
    ]
